# Generated by Django 6.0.1 on 2026-01-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='employee',
            new_name='user',
        ),
    ]
